### ISSUE TITLE
Speech Generation

### ISSUE THREAD

**Issue by populated** [shuttleai/shuttleai-python#10]
How does one expect to generate proper speech audio when the function only accepts `prompt` and `model`, but you can't provide a voice? :sob: (Synchronous)

**Comment by herumes** [comment]
Fixed as of `shuttleai==4.1.9`.
Ref: https://github.com/shuttleai/shuttleai-python/commit/fccaa79ed87f6a776c4c78958074837cf88cc8e2

Thank you for reporting
