### ISSUE TITLE
Possible Future Issue.

### ISSUE THREAD

**Issue by alluding** [shuttleai/shuttleai-python#2]
As of now, the library relies on the base URL `https://api.shuttleai.app/v1`. The problem with this is the hard-coded version `v1`. If any groundbreaking changes happen to the API, such as deprecation, etc., that would break this library. Maybe switch it to just `https://api.shuttleai.app/` and make it automatically use the latest API version (the API itself), but still allow `v1`, etc., similar to how Discord handles versioning.

**Comment by tristandevs** [comment]
oh

**Comment by tristandevs** [comment]
ok

**Comment by tristandevs** [comment]
ty

**Comment by tristandevs** [comment]
****

**Comment by herumes** [comment]
you can create a pr for this if youd like, if not, im sure itll be fixed/implemented whenever or if we decide to do other endpoints besides /v1 (we have discussed a /v2)
